version: "3"
services:
  backend:
    container_name: ppclothesBE
    build: .
    image: backend
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=flukefriendbest
    volumes:
      -  /home/ppclothes/backend/images:/public/img
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: NETWORK
